// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9l-dyE-AXOq_D5TMjzqbxWlgUn_rbTII',
    appId: '1:221331089463:web:355d374d8ea73e3a2237b2',
    messagingSenderId: '221331089463',
    projectId: 'bookswap-b074c',
    authDomain: 'bookswap-b074c.firebaseapp.com',
    storageBucket: 'bookswap-b074c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJkD52o4OyqdTTCx5Y0HlTf-nXfkHVYc',
    appId: '1:221331089463:android:abd342d1f26b368c2237b2',
    messagingSenderId: '221331089463',
    projectId: 'bookswap-b074c',
    storageBucket: 'bookswap-b074c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZ-Y710JnIQXaOuJYtzmLaJZ7ipc1Rvw',
    appId: '1:221331089463:ios:ce10ab09a47d4cb72237b2',
    messagingSenderId: '221331089463',
    projectId: 'bookswap-b074c',
    storageBucket: 'bookswap-b074c.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdZ-Y710JnIQXaOuJYtzmLaJZ7ipc1Rvw',
    appId: '1:221331089463:ios:ce10ab09a47d4cb72237b2',
    messagingSenderId: '221331089463',
    projectId: 'bookswap-b074c',
    storageBucket: 'bookswap-b074c.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9l-dyE-AXOq_D5TMjzqbxWlgUn_rbTII',
    appId: '1:221331089463:web:9c5cadb86dbc5b5d2237b2',
    messagingSenderId: '221331089463',
    projectId: 'bookswap-b074c',
    authDomain: 'bookswap-b074c.firebaseapp.com',
    storageBucket: 'bookswap-b074c.firebasestorage.app',
  );
}
